### ISSUE TITLE
Strings from block.json are not translated in Gutenberg

### ISSUE THREAD

**Issue by code-flow** [wp-cli/i18n-command#305] opened 2022-03-03 10:57 UTC
Hey there,
I guess I've found an issue regarding the translation of block.json content. I'm not quite sure where the exact problem is: WP-CLI or the Gutenberg project?

**Summary:**
After generating PO- and JSON-Files with the according CLI-commands Gutenberg does not translate strings from block.json.

**Steps to reproduce:**

1. Install a Test block
`cd /wp-content/plugins`
`npx @wordpress/create-block my-test-block`

2. Edit /src/index.js to use block-meta:
```
import metadata from './block.json';
registerBlockType(metadata, {
	edit: Edit,
	save,
});
```

3. Fix `editorScript` path in block.json (otherwise MD5-hashes are not correct)
```
{
	"editorScript": "file:index.js",
	...
}
```

4. Create POT
`cd /my-test-block`
`wp i18n make-pot . languages/my-test-block.pot --skip-php --exclude=build,node_modules`

5. Create PO-File and translate (at least the strings from the block.json)

6. Create JSON-File:
`cd languages`
`wp i18n make-json my-test-block-de_DE.po ./ --no-purge '--use-map={ "src/index.js": "build/index.js", "src/save.js": "build/index.js", "src/edit.js": "build/index.js", "src/block.json": "build/index.js" }'`

7. Run build
`cd wp-content/plugins/my-test-block`
`npm run build`

8. Fix path in my-test.block.php
```
add_filter(
	'load_script_translation_file',
	function ( string $file, string $handle, string $domain ) {
		if ( 'my-test-block' !== $domain ) {
			return (string) $file;
		}

		return plugin_dir_path( __FILE__ ) . 'languages/' . basename( $file );
	},
	10,
	3
);
```

8. Activate plugin and add the block into a post. Set language accordingly.
The title is not translated.

**Environment**
`wp cli info`
```
OS:     Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
Shell:  /bin/zsh
PHP binary:     /opt/homebrew/Cellar/php@7.4/7.4.28.reinstall/bin/php
PHP version:    7.4.28
php.ini used:   /opt/homebrew/etc/php/7.4/php.ini
MySQL binary:   
MySQL version:  
SQL modes:      
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/fs/Local Sites/meinwp/app/public/wp-content/plugins/my-test-block/languages
WP-CLI packages dir:    
WP-CLI global config:   /Users/fs/.wp-cli/config.yml
WP-CLI project config:  
WP-CLI version: 2.6.0
```

**Expected Result**
I would expect that the block title and the description gets translated.

**Actual Results**
Title and description gets not translated.

Any help is much appreciated.

**Comment by swissspidy** [comment] 2022-03-03 11:07
> I guess I've found an issue regarding the translation of block.json content. I'm not quite sure where the exact problem is: WP-CLI or the Gutenberg project?

As long as WP-CLI extracts all the expected strings from your code, then it's not a WP-CLI problem. Afterwards it's up to the project and developer to make use of it.

Can you you confirm that your PO/JSON file contains the block title as extracted from `block.json`? Can you share their contents here?

The file names of the JSON file names is usually a likely culprit, but you're overriding that manually, so it's up to you to provide the correct file paths & mappings.

**Comment by swissspidy** [comment] 2022-03-03 13:00
The output is **exactly** how Gutenberg expects it. Gutenberg also uses this context, as defined by the [`i18n-block.json`](https://github.com/WordPress/gutenberg/blob/71a63fd636b871b73e475821f94fa634e7550b92/packages/blocks/src/api/i18n-block.json) file (which is shared by WP-CLI and Gutenberg) and as used by [`translateBlockSettingUsingI18nSchema `](https://github.com/WordPress/gutenberg/blob/4ba530c55bf4271a41ccd640f84165584d8fefd0/packages/blocks/src/api/registration.js#L287-L328)

If you can put your code in a small GitHub repo or Gist I'm happy to look into it to help you find the issue, but from what I can see this is not a bug in WP-CLI.

**Comment by swissspidy** [comment] 2022-03-04 08:51
I am closing this because there is nothing wrong with the WP-CLI string extraction from what I can see.

My offer still stands, feel free to reach out via WordPress Slack so I can take a look at it.

In the future, the WordPress forums or StackOverflow would be a better place for getting i18n help.

**Closed by swissspidy** 2022-03-04 08:51 UTC
Labels: state:unconfirmed, command:i18n-make-pot, command:i18n-make-json
