### ISSUE TITLE
wp i18n make-pot fails with Fragment short syntax

### ISSUE THREAD

**Issue by MatzeKitt** [wp-cli/i18n-command#298] opened 2022-01-11 13:50 UTC
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I used a `<BaseControl>` with a `<>` inside it. As it is working in the code, I tried generating the POT file via `wp i18n make-pot` but the JavaScript file with this `<BaseControl>` wasn't part of the generated POT file. After using the `--debug` flag, the following error message were displayed for the file:

```
Debug (make-pot): Could not parse file src/test.js: Unexpected: > (line 6, column 3) (0.108s)
```

The `test.js` looks like this:

```js
import { BaseControl, UnitControl } from '@wordpress/components';
import { __ } from '@wordpress/i18n';

const foo = () => {
	<BaseControl>
		<>
			<UnitControl
				label={ __( 'Test', 'domain' ) }
			/>
		</>
	</BaseControl>
}
```

As soon as I remove the (not required) `<>` and `</>`, `wp i18n make-pot` succeeds.

**Describe how other contributors can replicate this bug**

- Add the test.js from above in your project.
- Run `wp i18n make-pot . languages/domain.pot --debug`

**Describe what you would expect as the correct outcome**

I would expect a successful parsing even with the fragment.

**Let us know what environment you are running this on**

```
OS:     Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
Shell:  /bin/zsh
PHP binary:     /opt/homebrew/Cellar/php@7.4/7.4.27/bin/php
PHP version:    7.4.27
php.ini used:   /opt/homebrew/etc/php/7.4/php.ini
MySQL binary:   /opt/homebrew/bin/mysql
MySQL version:  mysql  Ver 8.0.27 for macos12.0 on arm64 (Homebrew)
SQL modes:      
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/matze/project-x
WP-CLI packages dir:    
WP-CLI global config:   /Users/matze/.wp-cli/config.yml
WP-CLI project config:  
WP-CLI version: 2.5.0
```

**Comment by swissspidy** [comment] 2022-01-11 15:12
This sounds like a duplicate of #281

Run `wp cli update --nightly` to update WP-CLI and this package to the latest version. The issue should be fixed then.

**Closed** 2022-01-11 15:13 UTC
Labels: state:unconfirmed, command:i18n-make-pot
