### ISSUE TITLE
PHP i18n functions prefixed with a slash are ignored

### ISSUE THREAD

**Issue by dgwyer** [wp-cli/i18n-command#344] opened 2022-11-16 15:30 UTC
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

Running the latest version of `wp-cli` (2.7.1) i18n functions prefixed with a slash are ignored. I need to prefix with a slash as I'm using PHP namespaces in my project.

Minimal  reproducible example:

```php
<?php
// wp i18n make-pot . --domain=bar
\esc_html__('foo', 'bar'); // doesnt work
esc_html__('baz', 'bar'); // works
```

The output from the snippet above is:

```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2022-11-16T15:11:24+00:00\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"X-Generator: WP-CLI 2.7.1\n"
"X-Domain: bar\n"

#: test-plugin.php:4
msgid "baz"
msgstr ""
```

**Comment by swissspidy** [comment] 2022-11-16 16:22
Well that is surprising!

Looks like [the PHP functions scanner we're using](https://github.com/php-gettext/gettext/tree/4.x) doesn't properly extract such functions call, so unfortunately this will need to get fixed upstream.

**Comment by dgwyer** [comment] 2022-11-22 19:04
Just adding a note here that this isn't likely to be fixed in the Gettext repo any time soon due to time constraints; incase anyone from the wp-cli team is able to pick this up.

https://github.com/php-gettext/Gettext/issues/284#issuecomment-1321112613

**Comment by remcotolsma** [comment] 2022-12-07 10:49
It might be good to know that this seems to work well on PHP 7.4, but it goes wrong in PHP 8.

- Test on PHP 7.4 → https://github.com/remcotolsma/wp-cli-i18n-make-pot-issue-php-8/commit/41f1280765ff9427ca8679e374bbc43825fd316a
- Test on PHP 8.1 → https://github.com/remcotolsma/wp-cli-i18n-make-pot-issue-php-8/commit/e89b0292b48ccf9a8167f571a764a3b9c63ea9dd

A workaround is to run `wp i18n make-pot` on PHP `7.4`:

```
brew link --overwrite php@7.4
```

**Comment by swissspidy** [comment] 2022-12-07 12:35
Interesting, yeah that might be it. In any case, it needs a volunteer to submit a PR to the Gettext library to help fix this properly :)

**Comment by remcotolsma** [comment] 2022-12-07 12:39
The https://github.com/php-gettext/Gettext library is already moved on the version `5` and the new https://github.com/php-gettext/PHP-Scanner library uses https://github.com/nikic/php-parser. It is quite possible that https://github.com/nikic/php-parser has better support for fully qualified names (FQN) and the problem is therefore no longer an issue in the latest Gettext library?

**Comment by remcotolsma** [comment] 2022-12-07 13:32
> In any case, it needs a volunteer to submit a PR to the Gettext library to help fix this properly :)

I have come up with a fix and opened a PR:

- https://github.com/php-gettext/Gettext/pull/288/files

I don't have much experience with this, but I did my best to contribute.

**Comment by swissspidy** [comment] 2022-12-08 09:06
Awesome, thanks a lot! And it has been merged, too!

Once a new release of Gettext v4 has been released, we can update the dependency here & update our tests too. Then we should be all set.

**Comment by remcotolsma** [comment] 2022-12-09 10:40
ℹ️ Version `4.8.8` of `gettext/gettext` was released yesterday: https://github.com/php-gettext/Gettext/releases/tag/v4.8.8 🎉.

**Comment by swissspidy** [comment] 2022-12-09 18:03
Working on adding a test here: #344

* https://github.com/wp-cli/wp-cli-bundle/pull/466

**Closed** 2022-12-09 19:09 UTC
Labels: bug, help-wanted, command:i18n-make-pot
