### ISSUE TITLE
Invalid unprefixed json files generated from (unprefixed) theme's PO files

### ISSUE THREAD

**Issue by drzraf** [wp-cli/i18n-command#291] opened 2021-12-01 12:36 UTC
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

For WP themes, PO files contain a mention to the theme's Gettext `textdomain` but the filename itself is **NOT** prefixed (see https://developer.wordpress.org/reference/functions/load_theme_textdomain/#user-contributed-notes).
Still, JSON files **must** get the corresponding `textdomain` prefix in their filename in order to be loaded.
`make-json` does not support this.
 
**Describe how other contributors can replicate this bug**
```
$ ls mytheme/languages/
de_DE.po  en_GB.po de_DE.mo en_GB.mo theme.pot

$ grep Domain mytheme/languages/*
languages/de_DE.po:"X-Domain: ae\n"
languages/en_GB.po:"X-Domain: ae\n"

#  Run from mytheme/
$ wp i18n make-json languages --no-purge
Success: Created 2 files.

$ ls languages/
de_DE.po  en_GB.po de_DE.mo en_GB.mo theme.pot de_DE-c5e5c9f7d2ea648faea28f338649ca97.json en_GB-c5e5c9f7d2ea648faea28f338649ca97.json
```

=> These unprefixed files aren't considered. I need to rename them.
=> If I renamed the PO file, then PHP-based `__()` would stop working.

**Provide a possible solution**

- Another command option?
- Or identify whether we are extracting unprefixed files defining a text domain (proper to a theme) and output `textdomain` prefixed files?
- Workaround: `rename -d -e 's/^/THE-TEXTDOMAIN-/' languages/*json`

**Comment by swissspidy** [comment] 2021-12-01 12:50
Thanks for your report.

This sounds like a duplicate of #197

**Closed** 2021-12-01 12:55 UTC
Labels: bug, command:i18n-make-json
