### ISSUE TITLE
PHP extractor misses plural strings that use brackets in their discriminator

### ISSUE THREAD

**Issue by NielsdeBlaauw** [wp-cli/i18n-command#295] opened 2021-12-16 14:24 UTC
## Bug Report
- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
When running `make-pot` the i18n commando can not correctly extract plurals when there brackets in the discriminator.

This is much like #225, but for PHP.

The reproduction example below is a minimal reproduction. The original case for us was code generated by Twig, which looks like 

`echo sprintf(_n("Reading time: %s minute", "Reading time: %s minutes", ($context['x'] ?? null), "demo"), ($context['x'] ?? null));`

**Describe how other contributors can replicate this bug**

1. Create a php file with the following two string:
  ```php
echo sprintf(_n("Reading time: %s minute", "Reading time: %s minutes", (1), "demo"), 1);
echo sprintf(_n("Download time: %s minute", "Download time: %s minutes", 1, "demo"), 1));
  ```
2. run `wp i18n make-pot`
3. Check resulting pot file. Download time is available to translate. Reading time is not.

**Describe what you would expect as the correct outcome**
The resulting pot file should contain both Reading time and Download Time.

**Comment by swissspidy** [comment] 2021-12-17 14:19
This is a known bug in [the underlying gettext library](https://github.com/php-gettext/Gettext) we're using for extracting the function calls: https://github.com/php-gettext/Gettext/issues/229

It might not a bug in v5, but we're still on v4 due to PHP version requirements.

**Comment by swissspidy** [comment] 2022-01-19 10:17
It might be possible to fix this upstream in v4, but needs someone to write a PR.

**Comment by swissspidy** [comment] 2022-07-06 15:11
Since this is blocked by the upstream library and an easy workaround exists, I am closing this one for now

**Closed by swissspidy** 2022-07-06 15:11 UTC
Labels: bug, command:i18n-make-pot
